# This is the name of your Worker service.
name = "trading-sim-worker"

# This is the entrypoint for your Worker.
main = "worker/src/index.js"

# This is the date that you developed your Worker against.
compatibility_date = "2024-03-26"

# This section is used by `wrangler pages dev` to serve your assets.
# It is not used during production deployment.
[dev]
# When running `wrangler pages dev`, it will serve the `public` directory.
# Requests that are not found in the `public` directory will be forwarded to the Worker.
# This is a common setup for single-page applications.
pages = "public"

# This allows you to import ".csv" and other text files directly into your Worker code.
# The content of the file will be available as a string.
[[rules]]
type = "Text"
globs = ["**/*.csv"]
fallthrough = true
